version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'aural'
      POSTGRES_PASSWORD: 
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  mailcatcher: 
    #https://mailcatcher.me/
    image: schickling/mailcatcher:latest
    ports:
        # SMTP port for receiving
        - 1025:1025
        # Expose GUI over port 1080
        - 1080:1080

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server 
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash -c "rails db:schema:load && rails db:seed && puma -C config/puma.rb"
    ports:
      - '3000:3000'
    volumes:
      - '.:/aural'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/aural'
    env_file:
      - '.env'
  # ActionCable, once I figure out what it's good for 
  # cable:
  #   depends_on:
  #     - 'redis'
  #   build: .
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - '28080:28080'
  #   volumes:
  #     - '.:/aural'
  #   env_file:
  #     - '.env'

volumes:
  redis:
  postgres: